Component/table
gofynd/nitrozen-vue pull request #111
Opened 2023-02-16 09:46 UTC by iamayushy

Video Link For the component
[https://drive.google.com/file/d/1mzQajQaQX-nfwl9ZiU5l5Z30d-UsvtFM/view?usp=sharing](url)

2023-02-17 09:24 UTC, ShahRohan27 requested changes

2023-02-17 09:24 UTC, ShahRohan27 commented on src/base/variable.less
> +@FontMD: 16px;
Not needed, use rem

2023-02-17 09:24 UTC, ShahRohan27 commented on src/components/NTable/NTable.vue
> +  border-top: 1px solid @ColorPrimaryGrey40;
Please use rem everywhere

2023-02-17 09:24 UTC, ShahRohan27 commented on src/components/NTable/NTable.vue
> +  font-size: @rowfont;
use rem and try using the same casing for all variables

2023-02-17 10:19 UTC, ShahRohan27 commented
Also add on click row handlers.

2023-02-19 15:11 UTC, iamayushy commented
@ShahRohan27 made the required changes. 
1. Changed from px to rem
2. Removed the variables
3. Added onRowClick event

2023-02-23 09:39 UTC, hiteshs01 commented
Merging as initial commit for table component

2023-02-23 09:39 UTC, merged